services:
  recipes_${name}:
    image: 'stefanjarina/recipes-backend-${name}'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${port}:${port}'

networks:
  default:
    external:
      name: recipes
