set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]

[private]
default:
  @just --list --justfile {{justfile()}}

# Build the application
@build:
  echo "Building..."
  dotnet build

# Run the application
@run:
  echo "Running..."
  dotnet build

# Create DB container
@docker-run:
  docker compose up

# Shutdown DB container
@docker-down:
  docker compose down

# Clean the binary
[unix]
@clean:
  echo "Cleaning..."
  rm -rf Recipes.API/bin Recipes.API/binobj

# Clean the binary
[windows]
@clean:
  Write-Host "Cleaning..."
  rm -r -fo Recipes.API/bin Recipes.API/binobj

# Live Reload
@watch:
  dotnet watch --project Recipes.API
