GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO recipes_fiber;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO recipes_fiber;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO recipes_fiber;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO recipes_fiber;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO recipes_fiber;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO recipes_fiber;
