services:
  recipes_fiber:
    image: 'stefanjarina/recipes-backend-fiber'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

networks:
  default:
    external:
      name: recipes
